# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mom_pb2 as mom__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mom_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MOMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateQueue = channel.unary_unary(
                '/MOMService/UpdateQueue',
                request_serializer=mom__pb2.UpdateQueueRequest.SerializeToString,
                response_deserializer=mom__pb2.UpdateQueueResponse.FromString,
                _registered_method=True)
        self.UpdateTopic = channel.unary_unary(
                '/MOMService/UpdateTopic',
                request_serializer=mom__pb2.UpdateTopicRequest.SerializeToString,
                response_deserializer=mom__pb2.UpdateTopicResponse.FromString,
                _registered_method=True)


class MOMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTopic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MOMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQueue,
                    request_deserializer=mom__pb2.UpdateQueueRequest.FromString,
                    response_serializer=mom__pb2.UpdateQueueResponse.SerializeToString,
            ),
            'UpdateTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTopic,
                    request_deserializer=mom__pb2.UpdateTopicRequest.FromString,
                    response_serializer=mom__pb2.UpdateTopicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MOMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MOMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MOMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MOMService/UpdateQueue',
            mom__pb2.UpdateQueueRequest.SerializeToString,
            mom__pb2.UpdateQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MOMService/UpdateTopic',
            mom__pb2.UpdateTopicRequest.SerializeToString,
            mom__pb2.UpdateTopicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
