# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mom.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmom.proto\":\n\x12UpdateQueueRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\x12\x10\n\x08messages\x18\x02 \x03(\t\"&\n\x13UpdateQueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\":\n\x12UpdateTopicRequest\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\x10\n\x08messages\x18\x02 \x03(\t\"&\n\x13UpdateTopicResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x80\x01\n\nMOMService\x12\x38\n\x0bUpdateQueue\x12\x13.UpdateQueueRequest\x1a\x14.UpdateQueueResponse\x12\x38\n\x0bUpdateTopic\x12\x13.UpdateTopicRequest\x1a\x14.UpdateTopicResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEQUEUEREQUEST']._serialized_start=13
  _globals['_UPDATEQUEUEREQUEST']._serialized_end=71
  _globals['_UPDATEQUEUERESPONSE']._serialized_start=73
  _globals['_UPDATEQUEUERESPONSE']._serialized_end=111
  _globals['_UPDATETOPICREQUEST']._serialized_start=113
  _globals['_UPDATETOPICREQUEST']._serialized_end=171
  _globals['_UPDATETOPICRESPONSE']._serialized_start=173
  _globals['_UPDATETOPICRESPONSE']._serialized_end=211
  _globals['_MOMSERVICE']._serialized_start=214
  _globals['_MOMSERVICE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
